typst-common: fix helper scripts

diff --git a/bin/pull-typst-common b/bin/pull-typst-common
--- a/bin/pull-typst-common
+++ b/bin/pull-typst-common
@@ -2,15 +2,16 @@
 
 set -e
 
-if [ -d "lib" ]; then
-	echo "error: lib directory already exists" >&2
+if [ -d "typst-common" ]; then
+	echo "error: typst-common directory already exists" >&2
 	exit 1
 fi
 
-mkdir lib
-cd lib
+mkdir typst-common
+cd typst-common
 git init
 git remote add -f origin https://github.com/jo3-l/typst-common
 git remote set-url --push origin no-push # disable pushing
+git config core.sparseCheckout true
 echo "lib/" >> .git/info/sparse-checkout
 git pull origin main
